// ToDo : There is a much better way to do this... Dr. Hu, i hear you!
// 
// ToDo : Fix the location problem!
// 
// ToDo : Style it!
// 
// ToDo :   Put the Javascript in it's own file.
// ToDo :   Spin the whole thing into an array where the divs that are written to
//          are generated by the JavaScript and the CountDowns are pulled from a
//          source, Google API ... ?
// ToDo :

function ShowCurrentTime() {
    var current_time = new Date();
    
    console.log("Current time is : " + current_time);
}


function CountDownTimer(date_and_time_of_deadline, id) {
    
    var deadline = new Date(date_and_time_of_deadline);
    
    console.log("deadline = " + deadline);
    var _second = 1000;
    var _minute = _second * 60;
    var _hour = _minute * 60;
    var _day = _hour * 24;
    
    var timer;

    function showRemaining() {
        var now = new Date();
        var time_remaining = deadline - now;

        // If the time has passed...
        if (time_remaining < 0) {

            clearInterval(timer);
            document.getElementById(id).innerHTML = 'EXPIRED!';

            return;
        }

        var days = Math.floor(time_remaining / _day);
        var hours = Math.floor((time_remaining % _day) / _hour);
        var minutes = Math.floor((time_remaining % _hour) / _minute);
        var seconds = Math.floor((time_remaining % _minute) / _second);

        // Write it to the page!

        // First clear whatever was there. (just in case?)
        document.getElementById(id).innerHTML = '';

        // Next, have some boiler-plate! (Thanks Prof. Shwerm!)
        document.getElementById(id).innerHTML += '';

        // Finally, get to writing it...
        document.getElementById(id).innerHTML += '<b>FUCK ME!!</b><br> In : ';

        document.getElementById(id).innerHTML += '<b>' + days + '</b> days, ';
        document.getElementById(id).innerHTML += '<b>' + hours + '</b> hours, ';
        document.getElementById(id).innerHTML += '<b>' + minutes + '</b> minutes, ';
        document.getElementById(id).innerHTML += '<b>' + seconds + '</b> secs; ';

        document.getElementById(id).innerHTML += '<br> <b>My Shit Show Starts!!</b>';
    }

    // Update every second.
    timer = setInterval(showRemaining, 1000);
}

//CountDownTimer('02/19/2017 10:1 AM', 'countdown');

CountDownTimer('04/19/2016 2:00 AM CDT', 'countdown');

//Sun Feb 19 2017 10:01:00 GMT+0900
ShowCurrentTime();

// console.log("Hello?")